dist: xenial
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE petclinic;'
script: mvn test -Dspring-boot.run.profiles=mysql-travis
sudo: false
install: true

addons:
  sonarcloud:
    organization: "gii-is-dp1"
    token:
      secure: $SONAR

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean verify sonar:sonar -Pcoverage 